name: firebase_dart
version: 0.0.1
description: Firebase functionality written in pure Dart, for sharing code between Flutter, web, and server.
author: Tim Traversy <timtrav@gmail.com>
homepage: https://github.com/timtraversy/firebase_dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.12.0+1

dev_dependencies:
  test: ^1.3.4